spring:
  application:
    name: ayang-admin

  config:
    import:
      - optional:nacos:ayang-admin.yml?group=ayang-admin&refreshEnabled=true
      - optional:nacos:ayang-admin-datasource.yml?group=ayang-admin&refreshEnabled=true
      - optional:nacos:ayang-admin-mybatis.yml?group=ayang-admin&refreshEnabled=true
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: 3647e17d-3ba5-4b90-aba7-01b212fcff10

      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 3647e17d-3ba5-4b90-aba7-01b212fcff10
        group: ayang-admin
